/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

// Written by Ryan Foo

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "LFOWaveformTable.h"
#include "WaveformComponent.h"

//==============================================================================
/**
*/
class NebuloModAudioProcessorEditor : public AudioProcessorEditor,
                                      private Slider::Listener,
                                      private ComboBox::Listener,
                                      public Button::Listener
{
public:
    NebuloModAudioProcessorEditor (NebuloModAudioProcessor&);
    ~NebuloModAudioProcessorEditor();

    //==============================================================================
    // Component Override Methods
    void paint (Graphics&) override;
    void resized() override;
    // Slider Override Method
    void sliderValueChanged (Slider* slider) override;
    // Combo Box Override Method
    void comboBoxChanged (ComboBox *comboBoxThatHasChanged) override;
    // Button Override Method
    void buttonClicked(Button*) override;
    void buttonStateChanged(Button*) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    NebuloModAudioProcessor& processor;
    
    // Create GUI methods
    void createSlider(Slider &slider, Slider::SliderStyle style, double defaultVal,
                      double min, double max, double incr, std::string name);
    void createLabel(Label &label, std::string name);
    
    // Sliders
    Slider depthSlider;
    Slider rateSlider;
    Slider feedbackSlider;
    Slider mixSlider;
    
    // Menus
    ComboBox modMenu;
    ComboBox lfoMenu;
    
    // Texts
    Label depthText;
    Label rateText;
    Label feedbackText;
    Label mixText;
    Label fxText;

    // LFO Waveform Drawing
    Path waveRef;
    LFOWaveformTable LFO;
    
    // LFO Reset Button
    TextButton resetLFO;
    
    // Waveform Component
    WaveformComponent wavComponent;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (NebuloModAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
