/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "Flanger.h"
#include "Phaser.h"


//==============================================================================
/**
*/
class NebuloModAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    NebuloModAudioProcessor();
    ~NebuloModAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    const String getName() const override;

    int getNumParameters() override;
    float getParameter (int index) override;
    void setParameter (int index, float newValue) override;

    const String getParameterName (int index) override;
    const String getParameterText (int index) override;

    const String getInputChannelName (int channelIndex) const override;
    const String getOutputChannelName (int channelIndex) const override;
    bool isInputChannelStereoPair (int index) const override;
    bool isOutputChannelStereoPair (int index) const override;

    bool acceptsMidi() const override;
    bool producesMidi() const override;
    bool silenceInProducesSilenceOut() const override;
    double getTailLengthSeconds() const override;

    //==============================================================================
    int getNumPrograms() override;
    int getCurrentProgram() override;
    void setCurrentProgram (int index) override;
    const String getProgramName (int index) override;
    void changeProgramName (int index, const String& newName) override;

    //==============================================================================
    void getStateInformation (MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;
    
    float gain;

public:
    // Added by Ryan Foo and Tom Longabaugh

    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (NebuloModAudioProcessor)
    
    // Added by Ryan Foo

    /* Effect Control variables */
    
    // Delay for flanger (?)
    float flDelayVal;
    // LFO ms increases the delay by at the maximum
    float flDepthVal;
    // LFO frequency
    float flRateVal;
    // LFO waveform
    int flLfoWaveformVal;
    // Feedback Level (?)
    float flFeedbackVal;
    // Dry/Wet mix
    float flMixVal;
    
    // Added by Tom Longabaugh
    // Delay for flanger (?)
    float phsDelayVal;
    // LFO ms increases the delay by at the maximum
    float phsDepthVal;
    // LFO frequency
    float phsRateVal;
    // LFO waveform
    int phsLfoWaveformVal;
    // Feedback Level (?)
    float phsFeedbackVal;
    // Dry/Wet mix
    float phsMixVal;
    
    Flanger flanger;
    Phaser phaser;
    
    // GUI update functions
    void updateFlanger(void);
    void updatePhaser();
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
