/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "LFOWaveformTable.h"
// #include "SineTable.h"


//==============================================================================
/**
*/
class NebuloModAudioProcessorEditor  : public AudioProcessorEditor,
                                       private Slider::Listener,
                                       private ComboBox::Listener
{
public:
    NebuloModAudioProcessorEditor (NebuloModAudioProcessor&);
    ~NebuloModAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    
    void sliderValueChanged (Slider* slider) override;
    void comboBoxChanged (ComboBox *comboBoxThatHasChanged) override;
    void updatePath();
    
    void initialize_glut(void);

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    NebuloModAudioProcessor& processor;
    
    void createSlider(Slider &slider, Slider::SliderStyle style, double defaultVal,
                      double min, double max, double incr, std::string name);
    
    void createLabel(Label &label, std::string name);
    
    Slider gainSlider;
    
    // Sliders
    Slider depthSlider;
    Slider rateSlider;
    Slider feedbackSlider;
    Slider mixSlider;
    
    // Menus
    ComboBox modMenu;
    ComboBox lfoMenu;
    
    // Texts
    Label depthText;
    Label rateText;
    Label feedbackText;
    Label mixText;
    Label fxText;

    Label debugText;
    
    Path waveRef;
    LFOWaveformTable LFO;
    
    bool initDrawing;
    bool firstTime_flanger;
    bool firstTime_phaser;
    int effectChanged;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (NebuloModAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
