/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginEditor.h"

// Thanks Uri!!! So helpful man!
void NebuloModAudioProcessorEditor::createSlider(Slider &slider, Slider::SliderStyle style, double defaultVal, double min, double max, double incr, std::string name) {
    // these define the parameters of our slider object
    slider.setSliderStyle(style);
    slider.setRange(min, max, incr);
    slider.setTextBoxStyle (Slider::NoTextBox, false, 90, 0);
    slider.setPopupDisplayEnabled (true, this);
    slider.setTextValueSuffix(" " + name);
    slider.setValue(defaultVal);
    
    // set this class as the listener for the slider's callback function
    slider.addListener(this);
    
    // this function adds the slider to the editor
    addAndMakeVisible(&slider);
    slider.setVisible(false);
    
    slider.setComponentID(name);
    slider.isAlwaysOnTop();
}

void NebuloModAudioProcessorEditor::createLabel(Label &label, std::string name)
{
    label.setSize(100,50);
    label.setEnabled(true);
    label.setText(name, dontSendNotification);
    addAndMakeVisible(label);
    label.setVisible(false);
    label.isAlwaysOnTop();
}

//==============================================================================
NebuloModAudioProcessorEditor::NebuloModAudioProcessorEditor (NebuloModAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (700, 550);
    
    // EFFECT PARAMETER SIDE
    
    // Menu
    modMenu.setText("Select Modulation");
    modMenu.addItem("Flanger", 1);
    modMenu.addItem("Phaser", 2);
    modMenu.setEnabled(true);
    modMenu.setSize(180, 30);
    addAndMakeVisible(&modMenu);
    modMenu.addListener(this);
    
    // Create dah sliders!!!
    createSlider(depthSlider, Slider::LinearHorizontal, processor.flDepthVal, 0.0, 1.0, 0.01, "Depth");
    createSlider(rateSlider, Slider::LinearHorizontal, processor.flRateVal, 0.0, 20.0, 1.0, "Rate");
    createSlider(feedbackSlider, Slider::LinearHorizontal, processor.flFeedbackVal, 0.0, 100.0, 1.0, "Feedback");
    createSlider(mixSlider, Slider::LinearHorizontal, processor.flMixVal, 0.0, 1.0, 0.01, "Mix");
    
    // Create texts!
    createLabel(depthText, "Depth");
    createLabel(rateText, "Rate");
    createLabel(feedbackText, "Feedback");
    createLabel(mixText, "Mix");
    createLabel(debugText, "Debugger");
    
    fxText.setSize(200, 50);
    
    // Backgrounds
    //fxBackground->setColour(Colours::chocolate);
    //fxBackground->drawRoundedRectangle(0, 0, 300, 300, 5, 5);
    
    
    // LFO PARAMETER SIDE

    // Menu
    lfoMenu.setText("Select LFO Waveform");
    lfoMenu.addItem("Sine", 1);
    lfoMenu.addItem("Triangle", 2);
    lfoMenu.addItem("Sawtooth", 3);
    lfoMenu.addItem("Square", 4);
    lfoMenu.addItem("Custom", 5);
    lfoMenu.setSize(180, 30);
    addAndMakeVisible(&lfoMenu);
    lfoMenu.addListener(this);
    
    // LFO Wavetable
    addAndMakeVisible(debugText);
}

NebuloModAudioProcessorEditor::~NebuloModAudioProcessorEditor()
{
}

//==============================================================================
void NebuloModAudioProcessorEditor::paint (Graphics& g)
{
    // Wavetable graph init
    waveRef.startNewSubPath(40, 280);
    // waveRef.lineTo(270, 280);
    for (int i = 0; i < 1024; i++)
    {
        float x_axis = (i+1) * 15 / 64;
        //float y_axis = waveTable[i] * 20.0f;
        
        waveRef.lineTo(40 + x_axis, 280 /*+ y_axis*/);
    }

    float lineThickness = 2.0f;
    
    // Background
    g.fillAll (Colours::khaki);

    // Texts and Line Graph
    g.setColour (Colours::black);
    g.setFont (28.0f);
    g.drawFittedText ("Nebulo Mod", getLocalBounds(), Justification::bottomLeft, 1);
    g.setFont(16.0f);
    g.drawFittedText("by Ryan Foo and Tom Longabaugh", getLocalBounds(), Justification::bottomRight, 2);
    
    // Backgrounds son!!!
    g.setColour(Colours::ivory);
    g.fillRoundedRectangle(320, 160, 370, 250, 25);
    g.fillRoundedRectangle(20, 160, 280, 250, 25);
    
    // The line graph!!
    g.setColour(Colours::black);
    g.strokePath(waveRef, PathStrokeType(lineThickness));
}

void NebuloModAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..

    // Knobs!!!
    depthSlider.setBounds(350, 160, 250, 75);
    rateSlider.setBounds(350, 210, 250, 75);
    feedbackSlider.setBounds(350, 260, 250, 75);
    mixSlider.setBounds(350, 310, 250, 75);
    
    // Menus!!!
    modMenu.setBounds(390, 120, 200, 200);
    lfoMenu.setBounds(70, 120, 200, 200);
    
    // Texts!!!
    depthText.setBounds(610, 170, 25, 75);
    rateText.setBounds(610, 220, 25, 75);
    feedbackText.setBounds(610, 270, 25, 75);
    mixText.setBounds(610, 320, 25, 75);
    fxText.setBounds(450, 360, 100, 50);
    
    debugText.setBounds(350, 400, 150, 150);
}

void NebuloModAudioProcessorEditor::sliderValueChanged(Slider* slider)
{    
    // Update Flanger
    if (modMenu.getSelectedItemIndex() == 0)
    {
        if (slider->getComponentID().compare("Mix") == 0) {
            processor.flMixVal = slider->getValue();
        }
        else if (slider->getComponentID().compare("Depth") == 0) {
            processor.flDepthVal = slider->getValue();
            // debugText.setText("Changing the Depth dawg", dontSendNotification);
        }
        else if (slider->getComponentID().compare("Rate") == 0) {
            processor.flRateVal = slider->getValue();
        }
        else if (slider->getComponentID().compare("Feedback") == 0) {
            processor.flFeedbackVal = slider->getValue();
        }
        
        processor.updateFlanger();
    }
    // Update Phaser
    else if (modMenu.getSelectedItemIndex() == 1)
    {
        if (slider->getComponentID().compare("Mix") == 0) {
            processor.phsMixVal = slider->getValue();
        }
        else if (slider->getComponentID().compare("Depth") == 0) {
            processor.phsDepthVal = slider->getValue();
        }
        else if (slider->getComponentID().compare("Rate") == 0) {
            processor.phsRateVal = slider->getValue();
        }
        else if (slider->getComponentID().compare("Feedback") == 0) {
            processor.phsFeedbackVal = slider->getValue();
        }
        
        processor.updatePhaser();
    }
}

void NebuloModAudioProcessorEditor::comboBoxChanged(ComboBox *comboBoxThatHasChanged)
{
    // Update GUI 
    if ((modMenu.getSelectedItemIndex() == 0) || (modMenu.getSelectedItemIndex() == 1))
    {
        depthSlider.setVisible(true);
        rateSlider.setVisible(true);
        feedbackSlider.setVisible(true);
        mixSlider.setVisible(true);
        
        depthText.setVisible(true);
        rateText.setVisible(true);
        feedbackText.setVisible(true);
        mixText.setVisible(true);
        
        if (modMenu.getSelectedItemIndex() == 0)
        {
            fxText.setText("Flanger", dontSendNotification);
            
            // set the sliders to saved values
            depthSlider.setValue(processor.flDepthVal);
            rateSlider.setValue(processor.flRateVal);
            feedbackSlider.setValue(processor.flFeedbackVal);
            mixSlider.setValue(processor.flMixVal);
            
            //updatePath();
            
            // debugText.setText(std::to_string(mixSlider.getValue()), dontSendNotification);
        }
        else if (modMenu.getSelectedItemIndex() == 1)
        {
            fxText.setText("Phaser", dontSendNotification);
            
            // set the sliders to saved values
            depthSlider.setValue(processor.phsDepthVal);
            rateSlider.setValue(processor.phsRateVal);
            feedbackSlider.setValue(processor.phsFeedbackVal);
            mixSlider.setValue(processor.phsMixVal);
            
            // debugText.setText(std::to_string(depthSlider.getValue()), dontSendNotification);
        }
        
        addAndMakeVisible(fxText);
        fxText.setVisible(true);
    }
}

void NebuloModAudioProcessorEditor::updatePath(Graphics &g)
{
    // Clear the waveform
    waveRef.clear();
    // Line thickness
    float lineThickness = 2.0f;
    
    // Select waveform
    
    waveRef.startNewSubPath(40, 280);
    // waveRef.lineTo(270, 280);
    for (int i = 0; i < 1024; i++)
    {
        float x_axis = (i+1) * 15 / 64;
        // float y_axis = processor.waveformTable[i] * 15 / 64;
        
        waveRef.lineTo(40 + x_axis, 300 /*+ y_axis*/);
    }
    
    g.strokePath(waveRef, PathStrokeType(lineThickness));
}
